name: Save GitHub Traffic

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia à meia-noite (UTC)
  workflow_dispatch:     # permite rodar manualmente

jobs:
  traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get traffic data
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/traffic/views \
          > traffic.json

      - name: Save history
        run: |
          DATE=$(date +%F)
          UNIQUES=$(cat traffic.json | jq '.uniques')

          echo "$DATE,$UNIQUES" >> traffic.csv

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add traffic.csv
          git commit -m "update traffic" || echo "no changes"
          git push
